### ISSUE TITLE
Containerize

### ISSUE THREAD

**Issue by AFineDayFor** [megphillips91/parent-checklist-plugin#3]
Place the bugger in docker

- [ ] spesifications for supporting software
- [ ] scoping
- [ ] stub/base implimentation

**Comment by AFineDayFor** [comment]
current after `docker-compose up -d --build --force-recreate --remove-orphans`

```bash
schoolistit-api on  3-Containerize [✘!+] on 🐳 v19.03.12
➜ curl -LIA 'test' 'http://localhost:8080/plugin.php'
HTTP/1.1 200 OK
Date: Wed, 22 Jul 2020 06:04:02 GMT
Server: Apache/2.4.38 (Debian)
X-Powered-By: PHP/7.4.8
Content-Type: text/html; charset=UTF-8
```

**Comment by megphillips91** [comment]
I may not be using the master as the most up to date. I was running this project like I was the only one writing code...because I was. So let me check this and see what is the 'live' most current branch of my local and what is running on my demo. I have a bad habit of running 'off master'

Now that we are working together I will behave better and write better docblocks and comments and stay on master....

**Comment by megphillips91** [comment]
Whew...Looks like this one was all merged in. I know the react app repo is a big ole mess. Sorry. Part of that comes from my weakness at GitHub. Im fine working locally but sometimes I get frustrated when it wont let me overwrite master remote. I will get better at that.
